/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as AuthenticatedAnunciosIndexRouteImport } from './routes/_authenticated/anuncios.index'
import { Route as AuthenticatedAnunciosDemoRouteImport } from './routes/_authenticated/anuncios.demo'
import { Route as AuthenticatedAnunciosNovoRouteImport } from './routes/_authenticated/anuncios.novo'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated/pedidos.$orderId'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos.index'
import { Route as AuthenticatedProdutosProductIdRouteImport } from './routes/_authenticated/produtos.$productId'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos.novo'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as ApiPublicIntegracoesCallbackMarketplaceRouteImport } from './routes/api/public/integracoes/callback/$marketplace'
import { Route as ApiPublicMarketplacesWebhookMarketplaceRouteImport } from './routes/api/public/marketplaces/webhook/$marketplace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnunciosIndexRoute =
  AuthenticatedAnunciosIndexRouteImport.update({
    id: '/anuncios/',
    path: '/anuncios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnunciosDemoRoute =
  AuthenticatedAnunciosDemoRouteImport.update({
    id: '/anuncios/demo',
    path: '/anuncios/demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnunciosNovoRoute =
  AuthenticatedAnunciosNovoRouteImport.update({
    id: '/anuncios/novo',
    path: '/anuncios/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosProductIdRoute =
  AuthenticatedProdutosProductIdRouteImport.update({
    id: '/produtos/$productId',
    path: '/produtos/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegracoesCallbackMarketplaceRoute =
  ApiPublicIntegracoesCallbackMarketplaceRouteImport.update({
    id: '/api/public/integracoes/callback/$marketplace',
    path: '/api/public/integracoes/callback/$marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketplacesWebhookMarketplaceRoute =
  ApiPublicMarketplacesWebhookMarketplaceRouteImport.update({
    id: '/api/public/marketplaces/webhook/$marketplace',
    path: '/api/public/marketplaces/webhook/$marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ia': typeof AuthenticatedIaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/anuncios/demo': typeof AuthenticatedAnunciosDemoRoute
  '/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/produtos/$productId': typeof AuthenticatedProdutosProductIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/anuncios/': typeof AuthenticatedAnunciosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/api/public/integracoes/callback/$marketplace': typeof ApiPublicIntegracoesCallbackMarketplaceRoute
  '/api/public/marketplaces/webhook/$marketplace': typeof ApiPublicMarketplacesWebhookMarketplaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/ia': typeof AuthenticatedIaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/anuncios/demo': typeof AuthenticatedAnunciosDemoRoute
  '/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/produtos/$productId': typeof AuthenticatedProdutosProductIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/anuncios': typeof AuthenticatedAnunciosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/api/public/integracoes/callback/$marketplace': typeof ApiPublicIntegracoesCallbackMarketplaceRoute
  '/api/public/marketplaces/webhook/$marketplace': typeof ApiPublicMarketplacesWebhookMarketplaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/anuncios/demo': typeof AuthenticatedAnunciosDemoRoute
  '/_authenticated/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/produtos/$productId': typeof AuthenticatedProdutosProductIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/_authenticated/anuncios/': typeof AuthenticatedAnunciosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/api/public/integracoes/callback/$marketplace': typeof ApiPublicIntegracoesCallbackMarketplaceRoute
  '/api/public/marketplaces/webhook/$marketplace': typeof ApiPublicMarketplacesWebhookMarketplaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/documentos'
    | '/estatisticas'
    | '/estoque'
    | '/ia'
    | '/integracoes'
    | '/onboarding'
    | '/vendas'
    | '/visao-geral'
    | '/anuncios/demo'
    | '/anuncios/novo'
    | '/pedidos/$orderId'
    | '/produtos/$productId'
    | '/produtos/novo'
    | '/api/ai/chat'
    | '/anuncios/'
    | '/pedidos/'
    | '/produtos/'
    | '/api/public/integracoes/callback/$marketplace'
    | '/api/public/marketplaces/webhook/$marketplace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/documentos'
    | '/estatisticas'
    | '/estoque'
    | '/ia'
    | '/integracoes'
    | '/onboarding'
    | '/vendas'
    | '/visao-geral'
    | '/anuncios/demo'
    | '/anuncios/novo'
    | '/pedidos/$orderId'
    | '/produtos/$productId'
    | '/produtos/novo'
    | '/api/ai/chat'
    | '/anuncios'
    | '/pedidos'
    | '/produtos'
    | '/api/public/integracoes/callback/$marketplace'
    | '/api/public/marketplaces/webhook/$marketplace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/documentos'
    | '/_authenticated/estatisticas'
    | '/_authenticated/estoque'
    | '/_authenticated/ia'
    | '/_authenticated/integracoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/vendas'
    | '/_authenticated/visao-geral'
    | '/_authenticated/anuncios/demo'
    | '/_authenticated/anuncios/novo'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/produtos/$productId'
    | '/_authenticated/produtos/novo'
    | '/api/ai/chat'
    | '/_authenticated/anuncios/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/produtos/'
    | '/api/public/integracoes/callback/$marketplace'
    | '/api/public/marketplaces/webhook/$marketplace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiPublicIntegracoesCallbackMarketplaceRoute: typeof ApiPublicIntegracoesCallbackMarketplaceRoute
  ApiPublicMarketplacesWebhookMarketplaceRoute: typeof ApiPublicMarketplacesWebhookMarketplaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/': {
      id: '/_authenticated/anuncios/'
      path: '/anuncios'
      fullPath: '/anuncios/'
      preLoaderRoute: typeof AuthenticatedAnunciosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/demo': {
      id: '/_authenticated/anuncios/demo'
      path: '/anuncios/demo'
      fullPath: '/anuncios/demo'
      preLoaderRoute: typeof AuthenticatedAnunciosDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/novo': {
      id: '/_authenticated/anuncios/novo'
      path: '/anuncios/novo'
      fullPath: '/anuncios/novo'
      preLoaderRoute: typeof AuthenticatedAnunciosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$productId': {
      id: '/_authenticated/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/produtos/$productId'
      preLoaderRoute: typeof AuthenticatedProdutosProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integracoes/callback/$marketplace': {
      id: '/api/public/integracoes/callback/$marketplace'
      path: '/api/public/integracoes/callback/$marketplace'
      fullPath: '/api/public/integracoes/callback/$marketplace'
      preLoaderRoute: typeof ApiPublicIntegracoesCallbackMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplaces/webhook/$marketplace': {
      id: '/api/public/marketplaces/webhook/$marketplace'
      path: '/api/public/marketplaces/webhook/$marketplace'
      fullPath: '/api/public/marketplaces/webhook/$marketplace'
      preLoaderRoute: typeof ApiPublicMarketplacesWebhookMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedAnunciosDemoRoute: typeof AuthenticatedAnunciosDemoRoute
  AuthenticatedAnunciosNovoRoute: typeof AuthenticatedAnunciosNovoRoute
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
  AuthenticatedProdutosProductIdRoute: typeof AuthenticatedProdutosProductIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
  AuthenticatedAnunciosIndexRoute: typeof AuthenticatedAnunciosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedAnunciosDemoRoute: AuthenticatedAnunciosDemoRoute,
  AuthenticatedAnunciosNovoRoute: AuthenticatedAnunciosNovoRoute,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
  AuthenticatedProdutosProductIdRoute: AuthenticatedProdutosProductIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
  AuthenticatedAnunciosIndexRoute: AuthenticatedAnunciosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiPublicIntegracoesCallbackMarketplaceRoute:
    ApiPublicIntegracoesCallbackMarketplaceRoute,
  ApiPublicMarketplacesWebhookMarketplaceRoute:
    ApiPublicMarketplacesWebhookMarketplaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
